[application]
name = "foxhole-artillery-planner"
default_platform = "web"

[web.app]
title = "Foxhole Artillery Planner"

[[web.proxy]]
backend = "http://localhost:3000/graphql"

[[web.proxy]]
backend = "http://localhost:3000/static"
