[package]
name = "foxhole-shared"
version = "0.1.0"
edition = "2021"

[features]
default = ["uuid-support"]
uuid-support = ["dep:uuid"]

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"], optional = true }
